biped2:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  group_joint_position_controller:
    type: pos_controller_biped/GrpPosController
    joints:
      - left_abad_joint
      - right_abad_joint 
      - left_spring_rear_joint
      - left_spring_front_joint
      - left_rear_joint
      - left_front_joint
      - right_spring_rear_joint
      - right_spring_front_joint
      - right_rear_joint
      - right_front_joint
    left_abad_joint:
      pid: {p: 200.0, i: 0.01, d: 1.2}
    right_abad_joint:
      pid: {p: 200.0, i: 0.01, d: 1.2}
    left_spring_rear_joint:
      pid: {p: 150.0, i: 0.01, d: 0.001}
    left_spring_front_joint:
      pid: {p: 150.0, i: 0.01, d: 0.001}
    left_rear_joint:
      pid: {p: 0.0, i: 0.0, d: 0.0}
    left_front_joint:
      pid: {p: 0.0, i: 0.0, d: 0.0}
    right_spring_rear_joint:
      pid: {p: 150.0, i: 0.01, d: 0.001}
    right_spring_front_joint:
      pid: {p: 150.0, i: 0.01, d: 0.001}
    right_rear_joint:
      pid: {p: 0.0, i: 0.0, d: 0.0}
    right_front_joint:
      pid: {p: 0.0, i: 0.0, d: 0.0}
