biped:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  joint_abad_position_controller:
    type: effort_controllers/JointPositionController
    joints: left_abad_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

